
x-service-defaults: &service-defaults
  build: .
  depends_on:
    db:
      condition: service_healthy
  restart: always
  environment:
    ONEDRIVE_CLIENT_ID: ${ONEDRIVE_CLIENT_ID}
    ONEDRIVE_CLIENT_SECRET: ${ONEDRIVE_CLIENT_SECRET}
    ONEDRIVE_DRIVE_ID: ${ONEDRIVE_DRIVE_ID}
    ONEDRIVE_TENANT_ID: ${ONEDRIVE_TENANT_ID}
    DATABASE_USER: ${DATABASE_USER:-postgres}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    DATABASE_HOST: db
    DATABASE_NAME: ${POSTGRES_DB:-document_transfer}
  volumes:
    - .:/opt/app

services:
  api:
    <<: *service-defaults
    ports:
      - "3000:3000"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-document_transfer}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-document_transfer}"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  worker:
    <<: *service-defaults
    command: ./script/worker run

  docs:
    profiles:
      - docs
    build:
      dockerfile: docs.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/docs

volumes:
  postgres:
