#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'rackup'

require_relative '../lib/config/application'

config = DocumentTransfer::Config::Application.from_environment

# Configure and start the server.
server = Rackup::Server.new
server.options = server.options.merge(Port: config.port)
server.start
