on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Documentation
    environment: ${{ env.ENVIRONMENT || 'dev' }}
    env:
      BUCKET_NAME: ${{ env.BUCKET_NAME || 'dev.docs.cfa.codes' }}
      PREFIX: ${{ env.PREFIX || 'document-transfer-service' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material pymdown-extensions
      - run: mkdocs build
      - run: aws s3 sync ./site "s3://${BUCKET_NAME}/${PREFIX}" --recursive
